def generate_report(symptoms, disease, confidence, info):

    report = f"""
HealthGuide AI Assessment Report

Prediction:
{disease}

Confidence:
{confidence:.2f}%

Severity:
{info['severity']}

Symptoms Selected:
"""

    for symptom in symptoms:
        report += f"\n• {symptom.replace('_', ' ').title()}"

    report += f"""

Description:
{info['description']}

Recommendation:
{info['recommendation']}

Suggested Medications:
"""

    for medication in info["medications"]:
        report += f"\n• {medication}"

    report += """

-------------------------------------

DISCLAIMER

This assessment is generated by an Artificial Intelligence system and should not replace professional medical advice.

If symptoms become severe or life-threatening, visit the nearest hospital immediately.
"""

    return report
